name: Test Website
on:
  pull_request:
    branches: ["*"]
    types: "opened", "reopened"]

jobs:
  publish:
    name: Test Website
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 📦
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies 📦
        run: yarn install

      - name: Lint 🔍
        run: yarn run lint

      - name: Build site 🔨
        run: yarn run build
